### ISSUE TITLE
Hey per!

### ISSUE THREAD

**Issue by TomasRoj** [per1234/arduino-ci-script#25]
Very sorry that i write here but i dont have any contact to you. I saw that you forked my library. Do you want to contribute? Its projects with my friends. I am still finding someone whou would help, but cant find anyone.

**Comment by per1234** [comment]
I forked the library so that I could submit this pull request:
https://github.com/TomasRoj/BasicsLibrary/pull/1
So I already have contributed.

I'll submit another pull request once that one has been resolved.
