### ISSUE TITLE
install_ide("newest") installs 1.8.11-ms-store-1 and linux build fails

### ISSUE THREAD

**Issue by tobozo** [per1234/arduino-ci-script#30]
I was using this command in my travis.yml:

    `install_ide '("newest")'`

and the build failed when arduino-ci-script tried to install `1.8.11-ms-store-1`

https://travis-ci.org/tobozo/ESP32-Chimera-Core/builds/647062992

It was easily fixed by hardcoding the latest version but not that easy to spot as no error message is displayed whatsoever

**Comment by per1234** [comment]
Thanks so much for reporting this @tobozo! I'll make a fix and a release within the next few hours.
